apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ceph-test-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/chiju/rook-ceph-lab.git
    targetRevision: HEAD
    path: apps/ceph-test-apps
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
