apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ceph-block-storage
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/chiju/rook-ceph-lab.git
    targetRevision: HEAD
    path: apps/ceph-block-storage
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
