apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-scale
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chiju/rook-ceph-lab.git
    targetRevision: main
    path: apps/test-scale
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
